[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "paypal.payments"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["Payments", "Vendor/Paypal", "Area/Finance", "Type/Connector"]
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-paypal.payments"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
